Correction de la documentation
TBoileau/code-challenge pull request #55
Opened 2020-10-05 08:58 UTC by AlexandreGerault

2020-10-05 13:52 UTC, TBoileau requested changes

2020-10-05 13:52 UTC, TBoileau commented on README.md
> +* [Participer](#comment-participer-au-développement-)
Est-ce que tu es sûr que l'ancre fonctionnement toujours ? Car par défaut, je ne crois pas que les accents soient bien pris en compte, à confirmer.

2020-10-05 13:52 UTC, TBoileau commented on docs/front.md
> +* [Pré-compilateur, pattern & coding style](#pré-compilateur-pattern--coding-style)
Est-ce que tu es sûr que l'ancre fonctionnement toujours ? Car par défaut, je ne crois pas que les accents soient bien pris en compte, à confirmer.

2020-10-05 13:52 UTC, TBoileau commented on docs/index.md
> +        * [Déconnexion](#déconnexion)
Est-ce que tu es sûr que l'ancre fonctionnement toujours ? Car par défaut, je ne crois pas que les accents soient bien pris en compte, à confirmer.

2020-10-05 13:52 UTC, TBoileau commented on docs/index.md
> +        * [Répondre à un quiz](#répondre-à-un-quiz)
Est-ce que tu es sûr que l'ancre fonctionnement toujours ? Car par défaut, je ne crois pas que les accents soient bien pris en compte, à confirmer.

2020-10-05 13:52 UTC, TBoileau commented on docs/index.md
> +    * [Générer un cas d'utilisation](#générer-un-cas-dutilisation)
Est-ce que tu es sûr que l'ancre fonctionnement toujours ? Car par défaut, je ne crois pas que les accents soient bien pris en compte, à confirmer.

2020-10-05 14:09 UTC, AlexandreGerault commented
J'ai pris comme lien celui indiqué par GitHub quand on clique sur le petit icône de lien qui apparaît au survol d'un titre et ça fonctionne avec ceux-ci. Tu peux le tester sur la branche `hotfix/docfiles` du coup

2020-12-09 10:06 UTC, YaFou commented on README.md
> +* [Participer](#comment-participer-au-développement-)
Ca fonctionne de mon côté avec Firefox et Chrome.

2020-12-09 10:06 UTC, YaFou approved these changes

2020-12-09 14:52 UTC, TBoileau approved these changes

2021-04-21 09:21 UTC, merged